# schemas.py
from pydantic import BaseModel, Field

from app.utils.errors import ErrorCode


class LLMInfo(BaseModel):
    """Configuration class for LLM service settings.

    This class represents the configuration settings required for interacting
    with Google Cloud's Language Learning Models (LLM) via Vertex AI.

    Attributes:
        project_id (str): The Google Cloud project identifier where the LLM service is deployed.
        location (str): The geographical region where the Vertex AI model is deployed.
        text_model (str): The name/version of the Vertex AI model to be used. Defaults to "gemini-1.0-pro".
    """

    project_id: str = Field(..., description="Google Cloud project ID.")
    location: str = Field(..., description="Vertex AI model deployment region.")
    text_model: str = Field("gemini-1.0-pro", description="Vertex AI model name.")


class TextInput(BaseModel):
    """TextInput schema for text prompt input.

    Attributes:
        prompt (str): Text prompt for the model.
    """

    prompt: str = Field(..., description="Text prompt for the model.")


class TextOutput(BaseModel):
    """TextOutput is a Pydantic model used to represent the output text generated by the model.

    Attributes:
        answer (str): The generated text from the model.
    """

    answer: str = Field(..., description="Generated text from the model.")


class ErrorResponse(BaseModel):
    """Represents an error response model.
    This class defines the structure for error responses in the API,
    containing both an error code and a descriptive message.

    Attributes:
        error (ErrorCode): The error code enum value indicating the type of error.
        message (str): A human-readable message describing the error.
    """

    error: ErrorCode = Field(..., description="Error code.")  # ErrorCode を追加
    message: str = Field(..., description="Error message.")
